---
name: gitea

releases:
- name: gitea
  version: v1
  url: https://github.com/a2geek/gitea-bosh-release/releases/download/v1/gitea-bosh-release.tgz
  sha1: 8544759fc3e524561734319b0567bd11421fad29
- name: "bpm"
  version: "1.4.1"
  url: "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.4.1"
  sha1: "1d2f22a5d024cb34f6d7d2da3f1ee95e4a8cdd61"
- name: "os-conf"
  version: "22.3.0"
  url: "https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=22.3.0"
  sha1: "0f88a29315d8d9f900bb30a81c0eaf6d34a61639"

instance_groups:
- name: gitea
  instances: 1
  azs: [z1, z2, z3]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  jobs:
  - name: bpm
    release: bpm
  - name: git
    release: gitea
  - name: gitea
    release: gitea
    properties:
      admin:
        username: ((gitea_admin_username))
        email: ((gitea_admin_email))
      https:
        certificate: ((gitea_web.certificate))
        private_key: ((gitea_web.private_key))
      server:
        domain: ((gitea_server_domain))
      security:
        secret_key: ((gitea_secret_key))
        internal_token: ((gitea_internal_token))
      oauth2:
        jwt_secret: ((gitea_jwt_secret))
      registration:
        password: ((gitea_registration_password))

- name: action-runner
  instances: 2
  azs: [z1, z2, z3]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  jobs:
  - name: bpm
    release: bpm
  - name: git
    release: gitea
  - name: node20
    release: gitea
  - name: ca_certs
    release: os-conf
    properties:
      certs: ((gitea_web.certificate))
  - name: act_runner
    release: gitea
    properties:
      runner:
        capacity: 4
      registration:
        password: ((gitea_registration_password))

variables:
- name: gitea_ca
  type: certificate
  options:
    is_ca: true
    common_name: gitea_ca
    duration: 1095
- name: gitea_web
  type: certificate
  options:
    ca: gitea_ca
    common_name: ((gitea_server_domain))
    alternative_names: [((gitea_server_domain)), gitea.internal]
- name: gitea_registration_password
  type: password
- name: gitea_secret_key
  type: password
- name: gitea_internal_token
  type: password
- name: gitea_jwt_secret
  type: password
  options:
    length: 32  # required by Gitea

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000
  serial: false
