---
name: gitea

releases:
- name: gitea
  version: latest
- name: "bpm"
  version: "1.4.1"
  url: "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.4.1"
  sha1: "1d2f22a5d024cb34f6d7d2da3f1ee95e4a8cdd61"

instance_groups:
- name: gitea
  instances: 1
  azs: [z1, z2, z3]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  jobs:
  - name: bpm
    release: bpm

  - name: gitea
    release: gitea
    properties:
      admin:
        username: ((gitea_admin_username))
        email: ((gitea_admin_email))
      https:
        certificate: ((gitea_web.certificate))
        private_key: ((gitea_web.private_key))
      server:
        domain: ((gitea_server_domain))
      security:
        secret_key: ((gitea_secret_key))
        internal_token: ((gitea_internal_token))
      oauth2:
        jwt_secret: ((gitea_jwt_secret))

variables:
- name: gitea_ca
  type: certificate
  options:
    is_ca: true
    common_name: gitea_ca
    duration: 1095
- name: gitea_web
  type: certificate
  options:
    ca: gitea_ca
    common_name: ((gitea_server_domain))
    alternative_names: [((gitea_server_domain))]
- name: gitea_secret_key
  type: password
- name: gitea_internal_token
  type: password
- name: gitea_jwt_secret
  type: password
  options:
    length: 32  # required by Gitea

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000
  serial: false
